### ISSUE TITLE
Handle connectivity events/issues

### ISSUE THREAD

**Issue by raucao** [67P/hyperchannel#77]
At the moment Hyperchannel doens't handle any connectivity issues on its own.

**Comment by skddc** [comment]
I started looking into this today, and it looks like Sockethub and/or its IRC platform need some work, in addition to handling connectivity in Hyperchannel itself.

Issue 1: When Sockethub loses its online connection it basically doesn't know about it. It reports everything as being connected (`isConnected() called, returned true`) and doesn't reconnect after it itself regains a network connection. Sends are reported as completed during all of that, and will just not result in anything being sent to the IRC server.

Issue 2: When Hyperchannel loses its connection to Sockethub, it takes almost a minute for socket.io to tell it about the connection having timed out and its trying to reconnect. After having reconnected (when regaining connectivity), it won't try to resend whatever was sent before the disconnect (but not "completed" by SH). Also, subsequent new sends resulted in `"unable to decrypt"` from socket.io, so it seems like the session couldn't be resumed with the same encryption keys. But it also didn't try to set up a new session.

The latter is the more common case of course, as the client usually has much worse connectivity than a server. So number 2 is the one that is critical for MVP imo.

**Comment by silverbucket** [comment]
Yeah issue 1 is a known problem with communicating with IRC. Since there's no actual confirmation of any messages from the IRC end, and the TCP socket itself doesn't let me know of any state change, I don't know of any good way to verify that I'm still connected & that the IRC server is receiving the messages I'm sending. If anyone has any ideas I'm open to suggestions.

**Comment by skddc** [comment]
Pinging it would be the easiest option. Socket.io actually uses pings as well to determine connection state as far as I could see.

**Comment by silverbucket** [comment]
Pinging the IRC server? But that wouldn't tell me if I have a valid socket open. I'd need some sort of built in command (not an optional nickserv like thing) to get get an act of some sort to know everything is all good.

**Comment by silverbucket** [comment]
*ack

**Comment by galfert** [comment]
My Colloquy IRC client does a periodical `/WHO` command to every channel to get the current list of users in those channels.

**Comment by galfert** [comment]
Oh, I just saw that it sends an actual `/PING` command to the IRC server as well. 

http://www.livinginternet.com/r/ra_ping.htm

**Comment by silverbucket** [comment]
Hmm, thought I actually tried this before and it wasn't working, but now I'm not sure so will check again. I like the idea of a WHO command, since we need those anyway esp during reconnect / secondary connection

**Comment by skddc** [comment]
Any command that expects a response would work as a ping I think (no response in time -> offline).

Issue 2 is definitely the critical one though, as that one is happening pretty much every time you use it on a mobile.

**Comment by silverbucket** [comment]
@skddc could you capture the debug output from sockethub (service) during the time of:
1. connected, everything working
2. mobile connection drops out
3. reconnect
4. decryption issues

So I get an idea of what's happening on the back-end.

**Comment by skddc** [comment]
@silverbucket If you give me an SSH public key, I can add a user account to the `dev.kosmos.org` server for you. Adding [all of these](https://github.com/silverbucket.keys) is a bit much. :)

**Comment by skddc** [comment]
@silverbucket https://gitlab.com/kosmos/chef/issues/14

**Comment by skddc** [comment]
There's an actual PING command by the way: https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#PING

**Comment by galfert** [comment]
Yes, I mentioned that already in https://github.com/67P/hyperchannel/issues/77#issuecomment-275928030

**Comment by skddc** [comment]
Oops, I missed that when scanning the thread.

**Comment by skddc** [comment]
New Sockethub milestone to track the various issues: https://github.com/sockethub/sockethub/milestone/18

**Comment by silverbucket** [comment]
Hey guys, so one of the issues I've tracked down is that after a reconnect (the server is unreachable for whatever reason, and then socket.io automatically reconnects) the session no longer has access to the old credentials, so what I suggest is that hyperchannel listens for the `reconnect` event and then submits any existing credentials back to sockethub, along with a `join` for each channel (which will just ensure a new connection is made as soon as possible so that incoming messages will be routed to the app). 

Sockethub client can also listen for the `reconnect` event and when it happens, resend any `ActivityStreams` objects that exist on the client back to sockethub, so we establish as close to the same state as possible. I'm hesitant to do this automatically for credentials as that would require keeping our own cache of this in the client, while easier it may be a little insecure. Curious to know you guys' thoughts on this. Should we be as automatic and seamless as possible? or expose the tools and guide app developers to react in the appropriate ways to re-establish state after a reconnect.

**Comment by skddc** [comment]
> Should we be as automatic and seamless as possible? or expose the tools and guide app developers to react in the appropriate ways to re-establish state after a reconnect.

I for one am 100% convinced to always go for the former. As in this case the client doesn't lose connectivity to IRC, but just to Sockethub, I think it should only have to deal with *that* connection, not with re-joining IRC channels or re-sending credentials.

**Comment by silverbucket** [comment]
> Should we be as automatic and seamless as possible? or expose the tools and guide app developers to react in the appropriate ways to re-establish state after a reconnect.
> 
> I for one am 100% convinced to always go for the former. As in this case the client doesn't lose connectivity to IRC, but just to Sockethub, I think it should only have to deal with that connection, not with re-joining IRC channels or re-sending credentials.

After working with this issue over the course of hackerbeach, it's becoming more and more clear that - while there are definitely areas that Sockethub can improve it's robustness around connection handling (which I've been improving a lot), handling re-joining of rooms and things like this just don't really seem to be within the scope of a web-proxy such as sockethub. Keeping track of which rooms the user is in is client logic, just like when an IRC client disconnects, when it reconnects it has to re-join the rooms that have been configured to auto-join. So. while I am improving the way sockethub reports connection timeouts. The client itself should be responsible for reconnecting and joining the channels saved in the user config.

**Comment by raucao** [comment]
Closing in favor of creating specific new issues. The situation has been improved overall since the last comment as well.
